[simulation]
model = "Deffuant"
# rng_seed = 120 # Leaving this empty will pick a random seed

[io]
# n_output_network = 20 # Write the network every 20 iterations
n_output_agents = 1 # Write the opinions of agents after every iteration
print_progress = true # Print the iteration time ; if not set, then does not prints
output_initial = true # Print the initial opinions and network file from step 0. If not set, this is true by default.
start_output = 1 # Start writing out opinions and/or network files from this iteration. If not set, this is 1.

[model]
max_iterations = 1000 # If not set, max iterations is infinite

[Deffuant]
homophily_threshold = 0.2 # d in the paper; agents interact if difference in opinion is less than this value 
mu = 0.5 # convergence parameter; similar to social interaction strength K (0,0.5] 
use_network = false # If true, will use a square lattice Will throw if sqrt(n_agents) is not an integer
binary_vector = true # If true, this will be the multi-dimensional binary vector Deffuant model
dim = 5 # For the multi-dimensional binary vector Deffuant model, define the number of dimensions in each opinion vector 

[network]
number_of_agents = 1000
connections_per_agent = 0
